# -*- coding: utf-8 -*-

import unittest
from laonlp.tokenize import word_tokenize, sent_tokenize


class TestTokenizePackage(unittest.TestCase):
    def test_word_tokenize(self):
        self.assertIsNotNone(word_tokenize("ພາສາລາວໃນປັດຈຸບັນ."))

    def test_word_tokenize_long_repetitive_text(self):
        # Test case for issue: word_tokenize stuck with long repetitive text
        # This text was generated by LLM and caused infinite loop
        text = "ທ່ານ scott beaumont ປະທານ google ອາຊີ ອາຊີ - ປາຊີຟິກ ຕີລາຄາສູງບັນດາເສດຖະກິດເສດຖະກິດ - ໃນສະພາບສໍາຄັນຂອງໂລກສາມາດ ນໍາ ຕີລາຄາສູງຫຼາຍ; ວ່າມີບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາເສດຖະກິດເສດຖະກິດ, ແລະ ຍູ້ແຮງບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາບັນດາການເຄື່ອນໄຫວ ແລະ ຫວຽດນາມ."
        result = word_tokenize(text)
        # Should complete without hanging
        self.assertIsNotNone(result)
        self.assertIsInstance(result, list)
        self.assertGreater(len(result), 0)

    def test_sent_tokenize(self):
        self.assertEqual(
            sent_tokenize("ພາສາລາວໃນປັດຈຸບັນ.ນະຄອນຫຼວງວຽງຈັນ"),
            ["ພາສາລາວໃນປັດຈຸບັນ.", "ນະຄອນຫຼວງວຽງຈັນ"]
        )
